apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: canary-route
spec:
  port:
    targetPort: 80
  to:
    kind: Service
    name: node-service
    weight: 50 
  alternateBackends:
    - kind: Service
      name: node-service-prod
      weight: 30  
    - kind: Service
      name: node-service-test
      weight: 20