name: OpenShift

env:
  OPENSHIFT_SERVER: ${{ secrets.OPENSHIFT_SERVER }}
  OPENSHIFT_TOKEN: ${{ secrets.OPENSHIFT_TOKEN }}
  OPENSHIFT_NAMESPACE: ${{ secrets.OPENSHIFT_NAMESPACE }}

  APP_NAME: ""

  APP_PORT: ""

  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
  IMAGE_REGISTRY_USER: ${{ github.actor }}
  IMAGE_REGISTRY_PASSWORD: ${{ secrets.GHCR_TOKEN }}

  IMAGE_TAGS: "1.0.${{ github.run_number }}"

on:
  workflow_dispatch:
  push:
    # Edit to the branch(es) you want to build and deploy on each push.
    branches: [ "main" ]

jobs:
 
  openshift-ci-cd:
    name: Build and deploy to OpenShift
    runs-on: ubuntu-latest
    environment: production

    outputs:
      ROUTE: ${{ steps.deploy-and-expose.outputs.route }}
      SELECTOR: ${{ steps.deploy-and-expose.outputs.selector }}

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Determine app name
      if: env.APP_NAME == ''
      run: |
        echo "APP_NAME=$(basename $PWD)" | tee -a $GITHUB_ENV

    - name: Determine image tags
      if: env.IMAGE_TAGS == ''
      run: |
        echo "IMAGE_TAGS=latest ${GITHUB_SHA::12}" | tee -a $GITHUB_ENV

    # https://github.com/redhat-actions/buildah-build#readme
    - name: Build from Dockerfile
      id: build-image
      uses: redhat-actions/buildah-build@v2
      with:
        image: ${{ env.APP_NAME }}
        tags: ${{ env.IMAGE_TAGS }}
        context: ./Day3/capstone 
        dockerfiles: |
          ./Day3/capstone/docker/Dockerfile
        
    - name: Push to registry
      id: push-image
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-image.outputs.image }}
        tags: ${{ steps.build-image.outputs.tags }}
        registry: ${{ env.IMAGE_REGISTRY }}
        username: ${{ env.IMAGE_REGISTRY_USER }}
        password: ${{ env.IMAGE_REGISTRY_PASSWORD }}

    - name: Install oc
      uses: redhat-actions/openshift-tools-installer@v1
      with:
        oc: 4

    # https://github.com/redhat-actions/oc-login#readme
    - name: Log in to OpenShift
      uses: redhat-actions/oc-login@v1
      with:
        openshift_server_url: ${{ env.OPENSHIFT_SERVER }}
        openshift_token: ${{ env.OPENSHIFT_TOKEN }}
        insecure_skip_tls_verify: true
        namespace: ${{ env.OPENSHIFT_NAMESPACE }}
    - name: Capstone Database Deployment
      run: |
        export OPENSHIFT_NAMESPACE=${{ env.OPENSHIFT_NAMESPACE }}

        oc project "$OPENSHIFT_NAMESPACE"

        echo "Applying database manifests..."
        oc apply -f Day3/capstone/database

    - name: Capstone APP Deployment
      run: |
        export IMAGE=${{ steps.push-image.outputs.registry-path }}
        export OPENSHIFT_NAMESPACE=${{ env.OPENSHIFT_NAMESPACE }}

        echo "Using image: $IMAGE"

        # Ersetze IMAGE_PLACEHOLDER nur in der richtigen Datei
        sed -i "s|IMAGE_PLACEHOLDER|$IMAGE|g" Day3/capstone/kustomize/base/deployment.yaml

        oc project "$OPENSHIFT_NAMESPACE"

        echo "Applying base deployment..."
        oc apply -k Day3/capstone/kustomize/base || { echo "Base deployment failed!"; exit 1; }

        echo "Applying production deployment..."
        oc apply -k Day3/capstone/kustomize/overlays/prod || { echo "Production deployment failed!"; exit 1; }

        echo "Applying test deployment..."
        oc apply -k Day3/capstone/kustomize/overlays/test || { echo "Test deployment failed!"; exit 1; }

        echo "Fetching pod status..."
        oc get pods -n "$OPENSHIFT_NAMESPACE"

    - name: Capstone Apply Canary Route
      run: |
        export OPENSHIFT_NAMESPACE=${{ env.OPENSHIFT_NAMESPACE }}

        oc project "$OPENSHIFT_NAMESPACE"

        echo "Applying Canary Route..."
        oc apply -f Day3/capstone/canary || { echo "Canary Route deployment failed!"; exit 1; }
